### ISSUE TITLE
Cannot insert image on IE8

### ISSUE THREAD

**Issue by umbalaconmeogia** [80beans/wysihat-engine#7]
Select an image from the list (facebox window), but nothing is inserted into the editor.

Work around: In wysihat.js, edit WysiHat.Commands.insertImage(url) as following:
    function insertImage(url) {
      this.focus(); // This line is added.
      this.execCommand('insertImage', false, url);
    }

Reference:
http://social.msdn.microsoft.com/Forums/en-US/iewebdevelopment/thread/1b8bfc9d-0746-4bc4-b7ca-9ebe3132877b

**Comment by jeffkreeftmeijer** [comment]
Hi, 

Thanks for digging into this and finding a solution. However, since this is a WysiHat ( http://github.com/josh/wysihat ) bug, I'd like to ask you to create an issue there ( http://github.com/josh/wysihat/issues ), or even better, fork the project and apply the patch yourself! :)

Thanks again!
- Jeff
